### ISSUE TITLE
node-gyp install error

### ISSUE THREAD

**Issue by nptrsn** [filipenatanael/whatsapp-clone-react-native#29]
Hi there,

When I pull the repo and run `npm install` I get the following error regarding node-gyp.

```Failed to execute '/usr/local/Cellar/node/7.10.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=whatsapp-clone-react-native/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=whatsapp-clone-react-native/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown' (1)
../deps/grpc/src/core/lib/backoff/backoff.cc:23:10: fatal error: 'src/core/lib/gpr/useful.h' file not found
#include "src/core/lib/gpr/useful.h"```

Do you know what versions of node, node-gyp and npm are required to install this project? I tried changing a number of versions across dependencies, but nothing worked.

Love the project idea! Would love to get this up and running!

Thanks

**Comment by nptrsn** [comment]
Here is the full, expanded error log. This appears during `npm install`


```
gyp ERR! build error
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=whatsapp-clone-react-native/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=whatsapp-clone-react-native/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown"
gyp ERR! cwd whatsapp-clone-react-native/node_modules/grpc
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/7.10.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=whatsapp-clone-react-native/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=whatsapp-clone-react-native/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (whatsapp-clone-react-native/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/7.10.0/bin/node" "whatsapp-clone-react-native/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd whatsapp-clone-react-native/node_modules/grpc
node-pre-gyp ERR! node -v v13.0.1
node-pre-gyp ERR! node-pre-gyp -v v0.7.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/7.10.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=whatsapp-clone-react-native/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=whatsapp-clone-react-native/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown' (1)
../deps/grpc/src/core/lib/backoff/backoff.cc:23:10: fatal error: 'src/core/lib/gpr/useful.h' file not found
#include "src/core/lib/gpr/useful.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/backoff/backoff.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/7.10.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=whatsapp-clone-react-native/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=whatsapp-clone-react-native/node_modules/grpc/src/node/extension_binary/node-v79-darwin-x64-unknown"
gyp ERR! cwd whatsapp-clone-react-native/node_modules/grpc
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN react-navigation-drawer@2.5.0 requires a peer of react-native-gesture-handler@^1.0.12 but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-drawer@2.5.0 requires a peer of react-native-reanimated@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-drawer@2.5.0 requires a peer of react-native-screens@>=1.0.0 || >= 2.0.0-alpha.0 || >= 2.0.0-beta.0 || >= 2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-tabs@2.9.0 requires a peer of react-native-gesture-handler@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-tabs@2.9.0 requires a peer of react-native-reanimated@^1.0.0-alpha but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-tabs@2.9.0 requires a peer of react-native-screens@>=1.0.0 || >= 2.0.0-alpha.0 || >= 2.0.0-beta.0 || >= 2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-tab-view@2.15.1 requires a peer of react-native-gesture-handler@* but none is installed. You must install peer dependencies yourself.
npm WARN react-native-tab-view@2.15.1 requires a peer of react-native-reanimated@* but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-stack@1.10.3 requires a peer of react-native-gesture-handler@^1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-navigation-stack@1.10.3 requires a peer of react-native-screens@^1.0.0 || ^1.0.0-alpha but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.10.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.10.1 install script.
```
